#!/bin/bash

# Vercel 배포 가이드
echo "==================================="
echo "Vercel 배포 가이드"
echo "==================================="
echo ""
echo "1. Vercel 대시보드 접속:"
echo "   https://vercel.com/dashboard"
echo ""
echo "2. 프로젝트 선택:"
echo "   imagae 프로젝트 클릭"
echo ""
echo "3. 재배포 방법 A - Deployments 탭:"
echo "   - Deployments 탭 클릭"
echo "   - 최신 배포의 [...] 메뉴 클릭"
echo "   - 'Redeploy' 선택"
echo "   - 'Redeploy' 버튼 클릭"
echo ""
echo "4. 재배포 방법 B - Git Push:"
echo "   - GitHub 저장소로 푸시하면 자동 배포"
echo "   - git push origin main"
echo ""
echo "5. 환경 변수 확인:"
echo "   Settings > Environment Variables"
echo "   - GOOGLE_AI_API_KEY: 설정됨 ✓"
echo ""
echo "6. 배포 완료 후 테스트:"
echo "   - 프로젝트 URL 접속"
echo "   - 스토리 입력 테스트"
echo "   - 나노바나나프로 이미지 생성 확인"
echo ""
echo "==================================="
echo "배포 URL 예시:"
echo "https://imagae.vercel.app"
echo "또는"
echo "https://imagae-[random].vercel.app"
echo "==================================="
